// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZRTCK.InventoryManagement.Persistence;

#nullable disable

namespace ZRTCK.InventoryManagement.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260413142437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("OrderDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_date");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.HasKey("Id")
                        .HasName("pk_assignments");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryAssignmentRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("InventoryAssignmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inventory_assignment_id");

                    b.Property<string>("InventoryItemId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("inventory_item_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_assignment_row");

                    b.HasIndex("InventoryAssignmentId")
                        .HasDatabaseName("ix_inventory_assignment_row_inventory_assignment_id");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_inventory_assignment_row_inventory_item_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_inventory_assignment_row_person_id");

                    b.ToTable("inventory_assignment_row", (string)null);
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryCategoryField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_category_fields");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_fields_category_id");

                    b.ToTable("category_fields", (string)null);
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_date");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoice_id");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_id");

                    b.Property<string>("FactoryId")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("factory_id");

                    b.Property<int>("InventoryInvoiceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("inventory_invoice_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_code");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_inventory");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_inventory_category_id");

                    b.HasIndex("InventoryInvoiceId")
                        .HasDatabaseName("ix_inventory_inventory_invoice_id");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryItemField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CategoryFieldId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_field_id");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_id");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_item_fields");

                    b.HasIndex("CategoryFieldId")
                        .HasDatabaseName("ix_item_fields_category_field_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_fields_item_id");

                    b.ToTable("item_fields", (string)null);
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_obsolete");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("position");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rank");

                    b.HasKey("Id")
                        .HasName("pk_people");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryAssignmentRow", b =>
                {
                    b.HasOne("ZRTCK.InventoryManagement.Persistence.InventoryAssignment", "InventoryAssignment")
                        .WithMany("AssignmentRows")
                        .HasForeignKey("InventoryAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_assignment_row_assignments_inventory_assignment_id");

                    b.HasOne("ZRTCK.InventoryManagement.Persistence.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_assignment_row_inventory_inventory_item_id");

                    b.HasOne("ZRTCK.InventoryManagement.Persistence.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_assignment_row_people_person_id");

                    b.Navigation("InventoryAssignment");

                    b.Navigation("InventoryItem");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryCategoryField", b =>
                {
                    b.HasOne("ZRTCK.InventoryManagement.Persistence.InventoryCategory", "Category")
                        .WithMany("Fields")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_fields_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryItem", b =>
                {
                    b.HasOne("ZRTCK.InventoryManagement.Persistence.InventoryCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_categories_category_id");

                    b.HasOne("ZRTCK.InventoryManagement.Persistence.InventoryInvoice", "InventoryInvoice")
                        .WithMany("InventoryItems")
                        .HasForeignKey("InventoryInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_invoices_inventory_invoice_id");

                    b.Navigation("Category");

                    b.Navigation("InventoryInvoice");
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryItemField", b =>
                {
                    b.HasOne("ZRTCK.InventoryManagement.Persistence.InventoryCategoryField", "CategoryField")
                        .WithMany()
                        .HasForeignKey("CategoryFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_fields_category_fields_category_field_id");

                    b.HasOne("ZRTCK.InventoryManagement.Persistence.InventoryItem", "Item")
                        .WithMany("Fields")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_fields_inventory_item_id");

                    b.Navigation("CategoryField");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryAssignment", b =>
                {
                    b.Navigation("AssignmentRows");
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryCategory", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryInvoice", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("ZRTCK.InventoryManagement.Persistence.InventoryItem", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
